# Generated by Django 2.2.16 on 2022-12-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile/default.png', upload_to='profile/', verbose_name='фото'),
        ),
    ]
